ekf_filter:
  ros__parameters:
    # Frecuencia de predicción y publicación
    frequency: 50.0
    sensor_timeout: 0.1
    two_d_mode: true
    publish_tf: true

    world_frame:   "map"
    odom_frame:    "odom"
    base_link_frame: base_link
    imu0_frame: "imu1_link"
    imu1_frame: "imu2_link"

    imu0: "/imu/primary"
    imu1: "/imu/secondary"
    #   Publicar odometría nav_msgs/Odometry además de TF
    publish_odometry: true
    # Tag0 como odometría 0
   # ----------------------------------------------------------------
    # Reemplazamos odom0 y odom1 por pose0 y pose1
    # ----------------------------------------------------------------
    # Pose desde AprilTag 0:
     # Pose desde AprilTag 0:
    pose0: "/tag_odom_0"
    pose0_frame: "map"
    pose0_child_frame: "base_link"
    pose0_config: [true, true, false,
                   false, false, false,
                   false, false, true,
                   false, false, false]
    pose0_pose_covariance: [
      0.001, 0.0,   0.0,   0.0,   0.0,   0.0,
      0.0,   0.001, 0.0,   0.0,   0.0,   0.0,
      0.0,   0.0,   999.0, 0.0,   0.0,   0.0,
      0.0,   0.0,   0.0,   999.0, 0.0,   0.0,
      0.0,   0.0,   0.0,   0.0,   999.0, 0.0,
      0.0,   0.0,   0.0,   0.0,   0.0,   0.01
    ]

    # ----------------------------------------------------------------
    # Pose desde AprilTag 1:
    pose1: "/tag_odom_1"
    pose1_frame: "map"
    pose1_child_frame: "base_link"
    pose1_config: [true, true, false,
                   false, false, false,
                   false, false, true,
                   false, false, false]
    pose1_pose_covariance: [
      0.001, 0.0,   0.0,   0.0,   0.0,   0.0,
      0.0,   0.001, 0.0,   0.0,   0.0,   0.0,
      0.0,   0.0,   999.0, 0.0,   0.0,   0.0,
      0.0,   0.0,   0.0,   999.0, 0.0,   0.0,
      0.0,   0.0,   0.0,   0.0,   999.0, 0.0,
      0.0,   0.0,   0.0,   0.0,   0.0,   0.01
    ]


  
    imu0_config: [  
      false, false, false,    # pos_x,pos_y,pos_z
      false, false, false,    # vel_x,vel_y,vel_z   ← ¡tienen que ser false!
      false, false, false,    # ori_roll,ori_pitch,ori_yaw
      true,  true,  true,     # ang_vel_roll,ang_vel_pitch,ang_vel_yaw
      true,  true,  false ]     # lin_accel_x,lin_accel_y,lin_accel_z
    

    imu1_config: [  
      false, false, false,  
      false, false, false,  
      false, false, false,
      true,  true,  true,  
      true,  true,  false]

    imu0_queue_size: 5
    imu1_queue_size: 5
    imu0_remove_gravitational_acceleration: true
    imu1_remove_gravitational_acceleration: true
    imu0_linear_acceleration_covariance: [0.1, 0.0, 0.0, 
                                          0.0, 0.1, 0.0, 
                                          0.0, 0.0, 0.1]
    imu0_angular_velocity_covariance:      [0.1, 0.0, 0.0, 
                                            0.0, 0.1, 0.0, 
                                            0.0, 0.0, 0.1]
    imu1_linear_acceleration_covariance: [0.1, 0.0, 0.0, 
                                          0.0, 0.1, 0.0, 
                                          0.0, 0.0, 0.1]
    imu1_angular_velocity_covariance:      [0.1, 0.0, 0.0, 
                                          0.0, 0.1, 0.0, 
                                          0.0, 0.0, 0.1]

    # En ekf_filter.yaml
    odom2: /zero_twist
    odom2_config: [
      false,false,false,   # pos_x,pos_y,pos_z  (no usamos pose)
      false,false,false,   # ori_roll,ori_pitch,ori_yaw (no)
      true,  true, false,  # vx,   vy,   vz     ← sólo fusionamos vx,vy
      false,false,false,   # vroll,vpitch,vyaw (no)
      false,false,false    # ax,   ay,   az     (no aceleraciones)
    ]
    odom2_twist_covariance: [0.0001,0.0,0.0,  
                              0.0, 0.0001, 0.0, 
                               0.0,0.0,0.0001]

    