ekf_filter:
  ros__parameters:
    # Frecuencia de predicción y publicación
    frequency: 50.0
    sensor_timeout: 0.1
    two_d_mode: true
    publish_tf: true
    dynamic_process_noise_covariance: true
    world_frame:    "map"
    odom_frame:     "odom"
    base_link_frame: "base_link"

    # Marcos de los IMUs
    imu0_frame:   "imu1_link"
    imu1_frame:   "imu2_link"

    # Tópicos de IMU
    imu0: "/imu/primary"
    imu1: "/imu/secondary"

    # Publicar odometría nav_msgs/Odometry además de TF
    publish_odometry: true

    # ----------------------------------------------------------------
    # AprilTag 0 → odom0 (pose + orientación + velocidad implícita)
    # ----------------------------------------------------------------
    odom0: "/tag_odom_0"
    odom0_frame:      "map"
    odom0_child_frame: "base_link"
    odom0_config: [
      true, true, true,   # pos_x, pos_y, pos_z
      true, true, true, # vel_x, vel_y, vel_z
      false, false, false, # ori_roll, ori_pitch, ori_yaw
      false, false, false, # ang_vel roll/pitch/yaw
      false, false, false  # lin_accel x/y/z
    ]
    odom0_pose_covariance: [
      0.001, 0.0,   0.0,   0.0,   0.0,   0.0,
      0.0,   0.001, 0.0,   0.0,   0.0,   0.0,
      0.0,   0.0,   999.0, 0.0,   0.0,   0.0,
      0.0,   0.0,   0.0,   999.0, 0.0,   0.0,
      0.0,   0.0,   0.0,   0.0,   999.0, 0.0,
      0.0,   0.0,   0.0,   0.0,   0.0,   0.01
    ]

    # ----------------------------------------------------------------
    # AprilTag 1 → odom1
    # ----------------------------------------------------------------
    odom1: "/tag_odom_1"
    odom1_frame:      "map"
    odom1_child_frame: "base_link"
    odom1_config: [
      true, true, true,
      true, true, true,
      false, false, false,
      false, false, false,
      false, false, false
    ]
    odom1_pose_covariance: [
      0.001, 0.0,   0.0,   0.0,   0.0,   0.0,
      0.0,   0.001, 0.0,   0.0,   0.0,   0.0,
      0.0,   0.0,   999.0, 0.0,   0.0,   0.0,
      0.0,   0.0,   0.0,   999.0, 0.0,   0.0,
      0.0,   0.0,   0.0,   0.0,   999.0, 0.0,
      0.0,   0.0,   0.0,   0.0,   0.0,   0.01
    ]

    # ----------------------------------------------------------------
    # ZUPT (zero_twist) → odom2 (solo velocidades)
    # ----------------------------------------------------------------
    odom2: "/zero_twist"
    odom2_frame:      "base_link"
    odom2_child_frame: "base_link"
    odom2_config: [
      false, false, false,  # pos_x, pos_y, pos_z
      false, false, false,  # ori_roll, ori_pitch, ori_yaw
      true,  true, true,   # vel_x, vel_y, vel_z (solo vx, vy)
      true, true, true,  # ang_vel roll/pitch/yaw
      false, false, false   # lin_accel x/y/z
    ]
    odom2_twist_covariance: [1e-9,0.0,0.0, 0.0,1e-9,0.0, 0.0,0.0,1e-9]

    # ----------------------------------------------------------------
    # Configuración de IMUs
    # ----------------------------------------------------------------
    imu0_config: [
      false, false, false,
      false, false, false,
      false, false, false,
      true,  true,  true,
      true,  true,  false
    ]
    imu1_config: [
      false, false, false,
      false, false, false,
      false, false, false,
      true,  true,  true,
      true,  true,  false
    ]

    imu0_queue_size: 5
    imu1_queue_size: 5
    imu0_remove_gravitational_acceleration: true
    imu1_remove_gravitational_acceleration: true
    imu0_linear_acceleration_covariance: [0.1, 0.0, 0.0, 0.0, 0.1, 0.0, 0.0, 0.0, 0.1]
    imu0_angular_velocity_covariance:      [0.1, 0.0, 0.0, 0.0, 0.1, 0.0, 0.0, 0.0, 0.1]
    imu1_linear_acceleration_covariance: [0.1, 0.0, 0.0, 0.0, 0.1, 0.0, 0.0, 0.0, 0.1]
    imu1_angular_velocity_covariance:      [0.1, 0.0, 0.0, 0.0, 0.1, 0.0, 0.0, 0.0, 0.1]
