ekf_localization_node:
  frequency: 50  # The rate at which the filter will run (50 Hz)

  # Frame IDs
  map_frame: map
  odom_frame: odom
  base_link_frame: base_link
  world_frame: odom  # Can be map if you want a global reference

  # IMU settings for the first IMU
  imu0: /imu_data
  imu0_config: [false, false, false,  # X, Y, Z Position
                false, false, false,  # X, Y, Z Velocity
                true, true, true,     # X, Y, Z Acceleration
                false, false, false,  # Roll, Pitch, Yaw (optional, if not calculated from IMU)
                true, true, true]     # Angular velocity X, Y, Z

  imu0_differential: false
  imu0_remove_gravitational_acceleration: true

  # IMU settings for the second IMU
  imu1: /imu_data_2
  imu1_config: [false, false, false,  # X, Y, Z Position
                false, false, false,  # X, Y, Z Velocity
                true, true, true,     # X, Y, Z Acceleration
                false, false, false,  # Roll, Pitch, Yaw (optional)
                true, true, true]     # Angular velocity X, Y, Z

  imu1_differential: false
  imu1_remove_gravitational_acceleration: true

  publish_tf: true  # Make
