ekf_filter:
  ros__parameters:
    # Frecuencia de predicción y publicación
    frequency: 50.0
    sensor_timeout: 0.1
    two_d_mode: false
    publish_tf: true

    world_frame:   "odom"
    odom_frame:    "odom"
    base_link_frame: "imu1_link"

    imu0: "/imu/primary"
    imu1: "/imu/secondary"

     # NUNCA fusionamos vel_x/vel_y/vel_z (no existen en sensor_msgs/Imu)
    imu0_config: [false, false, false,   false, false, false,   true, true,  true,   true,  true,  true,   true,  true,  true]
    imu1_config: [false, false, false,   false, false, false,   true, true,  true,   true,  true,  true,   true,  true,  true]


    imu0_queue_size: 5
    imu1_queue_size: 5

    imu0_linear_acceleration_covariance: [0.1, 0.0, 0.0,
                                          0.0, 0.1, 0.0,
                                          0.0, 0.0, 0.1]
    imu0_angular_velocity_covariance:      [0.1, 0.0, 0.0,
                                          0.0, 0.1, 0.0,
                                          0.0, 0.0, 0.1]

    imu1_linear_acceleration_covariance: [0.2, 0.0, 0.0,
                                          0.0, 0.2, 0.0,
                                          0.0, 0.0, 0.2]
    imu1_angular_velocity_covariance:    [0.2, 0.0, 0.0,
                                          0.0, 0.2, 0.0,
                                          0.0, 0.0, 0.2]

    #   Publicar odometría nav_msgs/Odometry además de TF
    publish_odometry: true
    odom0: ""                 # sin fuentes “odom” externas
    odom0_config: [false, false, false,   false, false, false,   false, false, false,
                   false, false, false,    false, false, false]
